/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class snippets_jdk_jni_a2_HelloWorld */

#ifndef _Included_snippets_jdk_jni_a2_HelloWorld
#define _Included_snippets_jdk_jni_a2_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     snippets_jdk_jni_a2_HelloWorld
 * Method:    fromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_snippets_jdk_jni_a2_HelloWorld_fromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
