package snippets.embedded.database.hsqldb.a1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class ConnectionManager {
    public static void main(String[] args) throws ClassNotFoundException, SQLException {        
        Class.forName("org.hsqldb.jdbc.JDBCDriver");
        Connection conn = DriverManager.getConnection("jdbc:hsqldb:file:src/main/resources/snippets/embedded/database/hsqldb/a1/db;", "SA", "");
        conn.createStatement().executeUpdate("drop table if exists word");
        conn.createStatement().executeUpdate("drop table if exists pos");
        conn.createStatement().executeUpdate("create table word (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(45))");
        conn.createStatement().executeUpdate("create table pos (id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, word_id INTEGER, type VARCHAR(45))");
        
        PreparedStatement ps1 = conn.prepareStatement("insert into word (name) values (?)");
        PreparedStatement ps2 = conn.prepareStatement("select MAX(id) from word"); 
        PreparedStatement ps3 = conn.prepareStatement("insert into pos (word_id, type) values (?, ?)");
        PreparedStatement ps4 = conn.prepareStatement("select w.id, w.name, p.type from word w inner join pos p on w.id = p.word_id");
        
        int word_id = 0;
        ResultSet rs2, rs4;

        //1st 
        ps1.setString(1, "hand");
        ps1.executeUpdate();
        
        rs2 = ps2.executeQuery();       
        while(rs2.next()){
            word_id = rs2.getInt(1);           
        }
        
        ps3.setInt(1, word_id);
        ps3.setString(2, "noun");        
        ps3.executeUpdate();    
        
        ps3.setInt(1, word_id);
        ps3.setString(2, "verb");        
        ps3.executeUpdate();    
        
        //2nd 
        ps1.setString(1, "perfect");
        ps1.executeUpdate();
        
        rs2 = ps2.executeQuery();       
        while(rs2.next()){
            word_id = rs2.getInt(1);           
        }
        
        ps3.setInt(1, word_id);
        ps3.setString(2, "adj");        
        ps3.executeUpdate();    
        
        ps3.setInt(1, word_id);
        ps3.setString(2, "verb");        
        ps3.executeUpdate();    

        rs4 = ps4.executeQuery();       
        while(rs4.next()){
            System.out.println(rs4.getInt(1));           
            System.out.println(rs4.getString(2));
            System.out.println(rs4.getString(3));
        }
        
        // persistent record to db.script
        conn.createStatement().execute("SHUTDOWN"); 
    }
}
